upper()-------- returns string which all the characters are in upper case

lower()-------- returns string which all the characters are in lower case

islower()-- written true or false

isnumeric()-------written true or false
isalpha()-----------written true or false
istitle()









##string methods


1.   join()      : join() method will conncatinate two strings
2.  split()     : split() method will 
3.  replace():




In [0]:
str="Ruthvik...!"
s1=" "
s2="21646541"
print(str.upper());
print(str.lower());
print(str.isupper());
print(s1.isupper());
print(s2.isnumeric());
print(s1.isspace());
print(str.istitle());
print(str.split());


RUTHVIK...!
ruthvik...!
False
False
True
True
True
['Ruthvik...!']


In [0]:
print(",".join(["python","ruthvik","ss"]));

python,ruthvik,ss


In [0]:
s= "python programming is easy to learn"
list=s.split()
print(list);


['python', 'programming', 'is', 'easy', 'to', 'learn']


In [0]:
s="python programming is easy to learn"
print(s.replace("gra","c"));

python procmming is easy to learn


##python--- Tuples
a tuple is seq of set of objects is like list only

the differences are,
                      
                      the tuples cannot be changed unlike list

list will use square brakets hold objects [ ]

tuples will use paranthessis to hold objects( )

tuples doesnt accept assignment operators

tuples doesnt accept delete operator( del)

set of operations-----------

1.  update
2.   delete 
3.  inert 

use list for above operations

In [0]:
t1 = ("python","programming",1989,2019,"machine learning","AI")
t2 = (1,2,3,4,5,6,7)
print("t1[::-2]=",t1[::-2]);
print("t2[0]=",t2[0]);

t1[::-2]= ('AI', 2019, 'programming')
t2[0]= 1


In [0]:
t1 = (2019,528)
t2 =(1254,789,2019)
t3=t1+t2
print(t1);
print(t2);
print(t3);
max(t3)
print("max number in t1 is",max(t3));

(2019, 528)
(1254, 789, 2019)
(2019, 528, 1254, 789, 2019)
max number in t1 is 2019


##tuple methods


1.   len(tuple);- len of tuple
2.   max(tuple);-
3.  min(tuple);-




In [0]:
contacts = {}
def addcontact(name,phone):
  if name not in contacts:
    contacts[name] = phone
    print("contacts %s added"% name);
  else:
      print("contact %s already exists"% name);
  return
addcontact("customer care idea",9640964599)
addcontact("customer care jio",9640964599)
addcontact("customer care srujana",8522741936)


contacts customer care idea added
contacts customer care jio added
contacts customer care srujana added


In [0]:
def searchcontact(name):
  if name in contacts:
    print(name,":",contact[name]);
  else:
    print("%s does not exists"% name);
  return
searchcontact("anil")
searchcontact("ajay")
searchcontact("srujana tinnavara")
  

anil does not exists
ajay does not exists
srujana tinnavara does not exists


In [0]:
def importcontacts(newcontacts):
  contacts.update(newcontacts)
  print(len(newcontacts.keys()),"contacts added successfully");
  return
newcontacts = {'dinesh':9999999999,'akhil':8888888888}
importcontacts(newcontacts)

2 contacts added successfully


In [0]:
#delete
def deletecontacts(name):
    if name in contacts:
        del contacts[name]
        print(name,": is deleted from the contacts");
    else:
        print(name,"is not exists in the contacts");
    return
deletecontacts("srujana tinnavara")
deletecontacts("anil")

srujana tinnavara is not exists in the contacts
anil is not exists in the contacts


In [0]:
def updateContact(name,phone):
  if name in contacts:
    contacts[name]=phone
    print(name,":updated with new phone number")
  else:
    print(name,"not exist in the contacts")
  return
updateContact("dinesh",9632587412) 

dinesh :updated with new phone number


### packages and modules

**  package**;- collection of modules
** sub packages**;- its part of main package
module a single pythin file contains set of opperations(functions)



*package---->sub-package->modules-->functions

In [0]:
from math import floor as f1
f1(123.456)

123

In [0]:
import math
math.factorial(5)

120

In [0]:
import random
def generaterandomnumbers(n,lb,ub):
    for i in range(0,n):
      print(random.randint(lb,ub),end=" ");
    return
generaterandomnumbers(10,25,200)

194 122 182 92 168 95 85 185 64 56 

In [0]:
import math
a = help("math")
print(a);

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module is always available.  It provides access to the
    mathematical functions defined by the C standard.

FUNCTIONS
    acos(...)
        acos(x)
        
        Return the arc cosine (measured in radians) of x.
    
    acosh(...)
        acosh(x)
        
        Return the inverse hyperbolic cosine of x.
    
    asin(...)
        asin(x)
        
        Return the arc sine (measured in radians) of x.
    
    asinh(...)
        asinh(x)
        
        Return the inverse hyperbolic sine of x.
    
    atan(...)
        atan(x)
        
        Return the arc tangent (measured in radians) of x.
    
    atan2(...)
        atan2(y, x)
        
        Return the arc tangent (measured in radians) of y/x.
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(...)
        atanh(x)
        
        Return the inverse hyperbolic tangent of x.
    
    ceil(...)
        ceil(x)
        
 

In [0]:
import random
a = help("random")
print(a);

Help on module random:

NAME
    random - Random variable generators.

MODULE REFERENCE
    https://docs.python.org/3.6/library/random
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
        integers
        --------
               uniform within range
    
        sequences
        ---------
               pick random element
               pick random sample
               pick weighted random sample
               generate random permutation
    
        distributions on the real line:
        ------------------------------
               uniform
               triangular
               normal (Gaussian)
               lognormal
               negative exponential
               gamma
             

In [0]:
import random
def generaterandomnumbers(n,lb,ub):
    for i in range(0,n):
      print(random.randrange(lb,ub),end=" ");
    return
generaterandomnumbers(10,25,200)

137 30 150 90 45 174 74 62 189 103 

In [0]:
import random
def generaterandomnumbers(n,lb,ub):
    for i in range(0,n):
      print(random.
               pick(lb,ub),end=" ");
    return
generaterandomnumbers(10,25,200)

##file handling in python
file:- document containing info residing on the  permanent storage on the pendrive,pdf,csv files and etc...

file i/p : input and output


                                        keyboard as input
                                        screen as output
                                        
                                        
                                        read/write
                                        
                                        open() - open the file
                                        close() - close the file
                                        
                                        open(filename,"mode of the file")
                                        
                                        
                                        
       "r"  ---- it opens the file for reading
       
         "w" ----- the mode open th file writing 
                                                       
             if the file name is not present,
             it creates a new file and write some data into it
                                        

In [0]:
def createfile(filename):
    f= open(filename,"w")
    for i in range(10):
        f.write("this is %d line\n" % i)
    print("file is created successfully and data has written");
    f.close()
    return
createfile("file1.txt")               

file is created successfully and data has written


In [0]:
def readfile(filename):
  f = open(filename,"r")
  if f.mode == "r":
    x = f.read()
    print(x);
  f.close()
  return
readfile("file1.txt")

this is 0 line
this is 1 line
this is 2 line
this is 3 line
this is 4 line
this is 5 line
this is 6 line
this is 7 line
this is 8 line
this is 9 line



In [0]:
def createfile(filename):
    f= open(filename,"w")
    for i in range(10):
        f.write("test %d line\n" % i)
    print("file is created successfully and data has written");
    f.close()
    return
createfile("file1.txt")               

file is created successfully and data has written


In [0]:
import os

def createFolder(directory):
    try:
        if not os.path.exists(directory):
            os.makedirs(directory)
    except OSError:
        print ('Error: Creating directory. ' +  directory)
createFolder('./data/')        

In [0]:
#data to append
# function to append the data to existing file
def appenddata(filename):
    f = open(filename,"a")
    f.write("new line 1\n")
    f.write("new line")
    return
appenddata("file1.txt")

In [0]:
def dataanalysiswordcount(filename,word):
    f = open(filename,"r")
    if f.mode == "r":
        x = f.read()
        lst = x.split()
    cnt = lst.count(word)
    return cnt
print(dataanalysiswordcount("file1.txt","rest"))  

0


In [0]:
import re
def phonenumbervalidate(number):
    pattern = '^[6-9][0-9]{9}$|^[0][6-9][0-9]{9}$|[+][9][1][6-9][0-9]{9}$'
    phone = str(phone)
    if re.match(pattern,phone):
        return true
    return false
print(phonenumbervalidate(9919707971));
print(phonenumbervalidate(9900427793));
  

In [0]:
import re
def phonenumbervalidate(number):
    pattern = '^[6-9][0-9]{9}$|^[0][6-9][0-9]{9}$|[+][9][1][6-9][0-9]{9}$'
    phone = str(phone)
    if re.match(pattern,phone):
        return true
    return false
print(phonenumbervalidate(9919707971));
print(phonenumbervalidate

email id  vallidation
          :


In [0]:
import re
def validateemailid(email):
    pattern = "^[0-9a-z][0-9a-z_.]{4,13}[0-9a-z][@][a-z0-9]{3,18}[.]{2,4}$"
    if re.match(pattern,email):
      return True
    return False
print(validateemailid("anil.1889@gmail.com"));
print(validateemailid("$anil.1889@gmail.com"));

False
False


In [0]:
import re 
def password(password):
    pattern = "^[a-z][0-9][@,#,!,$][!]";
    if re.match(pattern,password):
      return False
    return True  
print(password("sonusonu145@"));    

True


In [0]:
import re 
def createfile(filename,email,number):
        pattern1 = "^[6-9][0-9]{9}$|^[0][6-9][0-9]{9}$|[+][9][1][6-9][0-9]{9}$"
        pattern2 = "^[0-9a-z][0-9a-z_.]{4,13}[0-9a-z][@][a-z0-9]{3,18}[.]{2,4}$"
  if re.match(pattern2,email):
      if re.match(pattern1,phone):
       f= open(filename,"w")
    for i in range(10):
        f.write("test %d line\n" % i)
    print("file is created successfully and data has written");
    f.close()
    return
    return True
    return False
createfile("file1.txt")
print(phonenumbervalidate(9919707971));
print(validateemailid("anil.1889@gmail.com"));

IndentationError: ignored

##Introduction to OOP'S in python:-  
 
                   One of the popular approach to solve a programming problem by creating an object.this is known as object oriented programming(OOP'S)
                   
                   An object has two characteristics:
                   1. attributes;--(age,name,colour)
                   2. behaviour;--(learn,study,dance)
                   
      in python, the concept OOP follow these things
                   
                   

In [0]:
class demo:
  def test(self):
      print("test() for class and method");
      return
obj= demo()
obj.test()

test() for class and method


In [0]:
class demo1:
  def fact(self,n):
    fact=1
    while(n!=0):
      fact=fact*n
      n=n-1
    return fact
p1=demo1()
print(p1.fact(89))


16507955160908461081216919262453619309839666236496541854913520707833171034378509739399912570787600662729080382999756800000000000000000000


In [0]:
class demo2:
    def _init_(self,p1,p2):
      self.p1= p1
      self.p2=p2
      
  def add(self,p1,p2):
      return p1+p2
  
c1 = demo2(10,20)
print(c1.add(100,200))

In [0]:
import numpy as np
lst = [1,2,3,4]
array = np.array(lst)
print(array)


a1=np.array([(1,2,3,),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(4,5,6)])
print(a2.shape)


a1=np.array([(1,2,3,),(4,5,6)])
print(a1)
a1.reshape(3,2)


a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))


a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[1 2 3 4]
(2, 3)
(2,)
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [0]:
a1= np.array([(1,2,3),(4,5,6)])
print("slicing last column:",a1[:,2]);

slicing last column: [3 6]


In [0]:

a1=np.random.normal(5,1,10)
print(a1);
print("min value=",np.min(a1));
print("max value=",np.max(a1));
print("mean value=",np.mean(a1));
print("median value=",np.median(a1));

[4.44949837 3.68693095 5.53659415 7.32293233 3.96973936 4.21455883
 4.68287422 3.81194831 4.02870444 5.95383463]
min value= 3.686930953533876
max value= 7.322932332216645
mean value= 4.765761558546745
median value= 4.332028598531759


In [0]:
c1=np.array([(1,2),(6,7)])
c2=np.array([(4,5),(8,9)])
np.dot(c1,c2)


array([[20, 23],
       [80, 93]])

In [0]:
 c1=np.array([(1,2),(6,7)])
c2=np.array([(4,5),(8,9)])
np.matmul(c1,c2)

array([[20, 23],
       [80, 93]])

##pandas basics



In [0]:
import pandas as pd
dict = {"Name":["arjun","rakeshprabhas","harsha","ruthviksonu","yuvi"],
        "EmailId":["arjun@gmail.com","rakeshprabhas@gmail.com","harsha@gmail.com","ruthviksonu@gmail.com","yuvi@gmail.com"],
        "MobileNumber":[181,984,999,143,985]}
b=pd.DataFrame(dict)
print(b)

            Name                  EmailId  MobileNumber
0          arjun          arjun@gmail.com           181
1  rakeshprabhas  rakeshprabhas@gmail.com           984
2         harsha         harsha@gmail.com           999
3    ruthviksonu    ruthviksonu@gmail.com           143
4           yuvi           yuvi@gmail.com           985


In [1]:
def countX(tup, x): 
    count = 0
    for ele in tup: 
        if (ele == x): 
            count = count + 1
    return count
tup = ( 8, 5, 2, 10, 15, 10, 8, 5, 8, 8, 2) 
enq = 4
enq1 = 10
enq2 = 8
print(countX(tup, enq)) 
print(countX(tup, enq1)) 
print(countX(tup, enq2)) 

0
2
4


In [4]:
#create series of numbers by passing a list of values
import pandas as pd
a = pd.Series([1,3,4,5,6,7])
print(a);

0    1
1    3
2    4
3    5
4    6
5    7
dtype: int64


In [7]:
# missing values then it can be 
import numpy as np
a1 = pd.Series([1,2,3,4,])
print(a1);

0    1
1    2
2    3
3    4
dtype: int64


In [0]:
dates = pd.date_range('2019878',periods=20)
print(dates);